theme: jekyll-theme-cayman
show_downloads: true
github:
  client_url: https://github.com/infclass/infclass-client/releases/latest
  server_url: https://github.com/infclass/teeworlds-infclassR/releases/latest
  teeuniverse_url: https://github.com/infclass/teeuniverse/releases/latest
